export const STORAGE_KEY_CLASSES = Object.freeze([
  'project',
  'preference',
  'secret-config',
  'disposable'
])

export const STORAGE_KEY_POLICY = Object.freeze({
  QUICK_NOTE_DRAFT: 'project',
  PROSE_QUICK_NOTE_DRAFT: 'project',
  WORLDBOOK_CREATE_DRAFT: 'project',
  WORLDBOOK_RESEARCH_SETTINGS: 'preference',

  WRITING_BOOKS: 'project',
  WRITING_CHARACTER: 'project',
  WRITING_TIME: 'project',
  WRITING_WORLDMAP: 'project',
  WRITING_SCENES: 'project',
  WRITING_ACTIVITIES: 'project',
  WRITING_CHARACTERS: 'project',
  WRITING_TIMELINES: 'project',
  WRITING_WORLD_SETTINGS: 'project',
  WRITING_NOTES: 'project',
  WRITING_SESSIONS: 'project',
  WRITING_SNAPSHOTS: 'project',
  WRITING_HISTORY_PREFERENCES: 'preference',
  WRITING_SIDEBAR_PREFERENCES: 'preference',
  WRITING_BLOCK_HISTORY: 'project',
  WRITING_RECOVERY_DRAFTS: 'project',
  WRITING_TYPOGRAPHY: 'preference',
  LOCAL_MIRROR_SETTINGS: 'preference',
  AUTHORING_REVIEW_RUNS: 'project',
  NARRATIVE_ASSETS: 'project',
  MEMORY_CANDIDATES: 'project',
  MEMORY_EXTRACTION_JOBS: 'project',
  STORYBOARD_DOCUMENTS: 'project',
  STORYBOARD_SNAPSHOTS: 'project',

  PROSE_CARDS_V1: 'project',
  PROSE_EDGES_V1: 'project',
  PROSE_OUTLINE_V1: 'project',
  PROSE_TIMELINE_V1: 'project',
  PROSE_PILES_V1: 'project',
  PROSE_COMMITS_V1: 'project',
  PROSE_BRANCHES_V1: 'project',
  PROSE_IMAGE_LIBRARY: 'project',

  POETRY_IDEA_TREE_V2: 'project',
  POETRY_IDEA_POSITIONS_V2: 'project',
  POETRY_ADAPT_PROFILE_V2: 'project',
  POETRY_GRAPH_EDGES_V1: 'project',
  POETRY_IMAGERY_GROUPS_V1: 'project',
  POETRY_SNAPSHOTS_V1: 'project',
  POETRY_IMAGE_LIBRARY_V1: 'project',

  IMAGE_MODEL_CONFIGS: 'secret-config',
  IMAGE_MODEL_SELECTED: 'preference',
  VIDEO_MODEL_CONFIGS: 'secret-config',
  VIDEO_MODEL_SELECTED: 'preference',
  MEDIA_ASSETS: 'project',
  IMAGE_GENERATION_RUNS: 'project',
  COMIC_PAGES: 'project',
  TEXT_MODEL_CONFIGS: 'secret-config',
  TEXT_MODEL_SELECTED: 'preference',

  PLAYABLE_WORLD_ENTRY_INTENT: 'project',
  GAME_SETTINGS: 'preference',
  WORKSPACE_TABS: 'preference',
  API_SETTINGS: 'secret-config',
  EXPERIENCE_READING_PROFILE: 'preference',
  EXPERIENCE_NARRATIVE_EXPANSION: 'preference',
  AGENT_RUNTIME_POLICY: 'preference',
  AGENT_RUNTIME_METRICS: 'disposable',
  NARRATIVE_PRODUCTION_METRICS: 'disposable',
  NARRATIVE_CRITIC_METRICS: 'disposable',

  CHARACTERS: 'project',
  PREFERENCE_USER_ID: 'preference',
  MEM0_SETTINGS: 'secret-config',
  PINAX_TIPS_SEEN: 'preference',
  EXPERIENCE_FIRST_VISIT: 'preference',
  GEOGRAPHY_DATA: 'project',
  WORLD_NODES: 'project'
})
